//// <auto-generated />
//using RxForEyeIPD.Data;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Migrations;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

//#nullable disable

//namespace CookieAuthCodingDroplet.Migrations
//{
//    [DbContext(typeof(AppDbContext))]
//    [Migration("20260207041907_initial")]
//    partial class initial
//    {
//        /// <inheritdoc />
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "8.0.0")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128);

//            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

//            modelBuilder.Entity("CookieAuthCodingDroplet.Model.Entities.UserAccount", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<string>("Password")
//                        .HasMaxLength(100)
//                        .HasColumnType("nvarchar(100)")
//                        .HasColumnName("password");

//                    b.Property<string>("Role")
//                        .HasMaxLength(20)
//                        .HasColumnType("nvarchar(20)")
//                        .HasColumnName("role");

//                    b.Property<string>("UserName")
//                        .HasMaxLength(100)
//                        .HasColumnType("nvarchar(100)")
//                        .HasColumnName("user_name");

//                    b.HasKey("Id");

//                    b.ToTable("user_accounts");

//                    b.HasData(
//                        new
//                        {
//                            Id = 1,
//                            Password = "123",
//                            Role = "Admin",
//                            UserName = "Rasel"
//                        },
//                        new
//                        {
//                            Id = 2,
//                            Password = "123",
//                            Role = "User",
//                            UserName = "Rubel"
//                        });
//                });

//            modelBuilder.Entity("CookieAuthCodingDroplet.Model.Entities.UserAccountPolicy", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int")
//                        .HasColumnName("id");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

//                    b.Property<bool>("IsEnabled")
//                        .HasColumnType("bit")
//                        .HasColumnName("is_enabled");

//                    b.Property<int>("UserAccountId")
//                        .HasColumnType("int")
//                        .HasColumnName("user_account_id");

//                    b.Property<string>("UserPolicy")
//                        .HasColumnType("nvarchar(max)")
//                        .HasColumnName("user_policy");

//                    b.HasKey("Id");

//                    b.ToTable("user_account_policy");

//                    b.HasData(
//                        new
//                        {
//                            Id = 1,
//                            IsEnabled = true,
//                            UserAccountId = 1,
//                            UserPolicy = "VIEW_PRODUCT"
//                        },
//                        new
//                        {
//                            Id = 2,
//                            IsEnabled = false,
//                            UserAccountId = 1,
//                            UserPolicy = "ADD_PRODUCT"
//                        },
//                        new
//                        {
//                            Id = 3,
//                            IsEnabled = true,
//                            UserAccountId = 1,
//                            UserPolicy = "EDIT_PRODUCT"
//                        },
//                        new
//                        {
//                            Id = 4,
//                            IsEnabled = false,
//                            UserAccountId = 1,
//                            UserPolicy = "DELETE_PRODUCT"
//                        },
//                        new
//                        {
//                            Id = 5,
//                            IsEnabled = false,
//                            UserAccountId = 2,
//                            UserPolicy = "VIEW_PRODUCT"
//                        },
//                        new
//                        {
//                            Id = 6,
//                            IsEnabled = false,
//                            UserAccountId = 2,
//                            UserPolicy = "ADD_PRODUCT"
//                        },
//                        new
//                        {
//                            Id = 7,
//                            IsEnabled = true,
//                            UserAccountId = 2,
//                            UserPolicy = "EDIT_PRODUCT"
//                        },
//                        new
//                        {
//                            Id = 8,
//                            IsEnabled = true,
//                            UserAccountId = 2,
//                            UserPolicy = "DELETE_PRODUCT"
//                        });
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
