use db_RxForEyeIPD
set nocount on

declare @TableNameString as varchar(50) = ''

declare @TableCreatorString varchar(4000) = '',  @TableName varchar (100), @EntityCreatorRow varchar(200), @Counter int = 2

if object_id ('TableCreatorFirst') is not null
drop table TableCreatorFirst

select * into TableCreatorFirst from OPENROWSET('Microsoft.ACE.OLEDB.12.0',  'Excel 8.0;HDR=YES;Database=E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Files\02. WithoutPrimaryAndWithForeignKey\TableCreateWithoutPrimaryAndWithForeignKey.xlsx', 'select * from [TblUsers$]') 


if object_id ('TableCreator') is not null
drop table TableCreator

select ROW_NUMBER() OVER (ORDER BY Slno asc) as SlNo, Particulars, ColumnName, ValueType, Amount, Nullable, DefaultValue, ChildRow, Method, Tbl, Val, Txt, ValidationMessage into TableCreator from TableCreatorFirst order by SlNo asc


set @TableName = (select ColumnName from TableCreator where particulars = 'TableName')


set @TableCreatorString = (select 'IF EXIST "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\" RMDIR ^/S ^/Q "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\"')
EXEC xp_cmdshell @TableCreatorString

set @TableCreatorString = (select 'mkdir "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\"')
EXEC xp_cmdshell @TableCreatorString


set @TableCreatorString = (select 'echo @page "/Settings/LocationMaster/' + @TableName +'/ComponentScript/GridviewAndDelete/' + lower(@TableName) +'" >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo @rendermode InteractiveServer >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo @inject I' + @TableName +' '+ @TableName +'Service >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo @inject NavigationManager Nav >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo ^<PageTitle^>List of '+ @TableName +'^<^/PageTitle^> >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo ^<h3^>List of '+ @TableName +'^<^/h3^> >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo ^<div class="row pb-2"^> >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo ^<div class="col-12 text-end"^> >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo @* Set your href manually according to your need. *@ >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo ^<a class="btn btn-sm btn-primary" href="/Settings/LocationMaster/' + @TableName +'/ComponentScript/SaveAndUpdate/SaveAndUpdate' + @TableName +'/' + @TableName +'"^> >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo New Entry >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo ^<^/a^> >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo ^<^/div^> >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo ^<^/div^> >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo ^<div class="row pb-2"^> >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo ^<div class="col-md-12"^> >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo ^<SfGrid DataSource="@' + @TableName +'s" AllowPaging="true"^> >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo ^<GridPageSettings PageSize="5"^>^<^/GridPageSettings^> >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo ^<GridColumns^> >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString

	set @Counter = 2

		while ((select (count(*) + 2) Total from TableCreator  where particulars in ('PrimaryID',  'Column')) > @Counter)
			begin
				set @TableCreatorString = (select 'echo ^<GridColumn Field="'+ (select ColumnName from TableCreator where SlNo = @Counter) +'" HeaderText="'+ (select ColumnName from TableCreator where SlNo = @Counter) +'" Width="100"^>^<^/GridColumn^> >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"')
				EXEC xp_cmdshell @TableCreatorString
				set @Counter +=1
            end

--set @TableCreatorString = (select 'echo ^<GridColumn Field="DivisionId" HeaderText="ID" Width="100"^>^<^/GridColumn^> >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
--set @TableCreatorString = (select 'echo ^<GridColumn Field="DivisionName" HeaderText="Division Name" Width="100"^>^<^/GridColumn^> >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
--set @TableCreatorString = (select 'echo ^<GridColumn Field="Population" HeaderText="Population" Width="100"^>^<^/GridColumn^> >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
--set @TableCreatorString = (select 'echo ^<GridColumn Field="SectorNumber" HeaderText="Sector" Width="100"^>^<^/GridColumn^> >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString


set @TableCreatorString = (select 'echo ^<GridColumn HeaderText="Actions" Width="100"^> >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo ^<Template^> >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo @{ >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo var row = context as ' + @TableName +'Entity; >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo } >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo ^<div class="d-flex gap-2"^> >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo ^<button class="btn btn-sm btn-primary" @onclick="() => Edit' + @TableName +'(row.'+ (select ColumnName from TableCreator  where particulars in ('PrimaryID'))  +')"^> >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo Edit >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo ^<^/button^> >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo ^<button class="btn btn-sm btn-danger" @onclick="async () => await Delete' + @TableName +'(row.'+ (select ColumnName from TableCreator  where particulars in ('PrimaryID'))  +')"^> >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo Delete >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo ^<^/button^> >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo ^<^/div^> >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo ^<^/Template^> >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo ^<^/GridColumn^> >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo ^<^/GridColumns^> >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo ^<^/SfGrid^> >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo ^<^/div^> >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo ^<^/div^> >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo @code { >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo public List^<' + @TableName +'Entity^> ' + @TableName +'s = new(); >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo private ' + @TableName +'Entity ' + @TableName +'Entity = new(); >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo protected override async Task OnInitializedAsync() >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo { >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo ' + @TableName +'s = await ' + @TableName +'Service.GetAll' + @TableName +'(); >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo } >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo void Edit' + @TableName +'(int id) >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo { >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo Nav.NavigateTo($"/Settings/LocationMaster/' + @TableName +'/ComponentScript/SaveAndUpdate/SaveAndUpdate' + @TableName +'/' + @TableName +'/{id}"); >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo } >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo private async Task Delete' + @TableName +'(int id) >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo { >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString


set @TableCreatorString = (select 'echo ' + @TableName +'Entity.'+ (select ColumnName from TableCreator  where particulars in ('PrimaryID'))  +' = id; >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo ' + @TableName +'Entity.DeletedBy = 1; >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString


set @TableCreatorString = (select 'echo var result = await ' + @TableName +'Service.Delete' + @TableName +'(' + @TableName +'Entity); >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo if (result ^> 0) >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo { >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo ' + @TableName +'s = await ' + @TableName +'Service.GetAll' + @TableName +'();^/^/ Optionally show a success message >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo } >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo else >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo { >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo ^/^/ Optionally show an error message >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo } >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo } >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
set @TableCreatorString = (select 'echo } >> "E:\DotNetCoreProjects\RxForEyeIPD\RxForEyeIPD\Components\Pages\DynamicFileCreator\' + @TableName +'\ComponentScript\GridviewAndDelete\GridviewAndDelete'+ upper(substring(@TableName, 1,1)) + substring(@TableName, 2,50) +'.razor"') EXEC xp_cmdshell @TableCreatorString
